# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://working-man-needs-money.github.io
title: Working Man | Needs Money
email: bunkertimothy0@gmail.com
author: Timothy Bunker
description: > # "The landing Pahe for every working man in need of money""
copyright: 'Copyright &copy; 2015 Timothy Bunker. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
logo: /WMNM/img/logos/working-man-logo-512x512.png

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Working-Man-Needs-Money/WMNM
  - title: notion
    url: https://www.notion.so/1c1c40f3f82a8065b260ea9466e6668a?v=1c1c40f3f82a80259109000c3a257952&pvs=4
    icon: /img/logos/notion-logo.png
  - title: projects
    url: https://github.com/orgs/Working-Man-Needs-Money/projects/2/
    icon: /img/logos/project-logo.png
